name: camp-vqa
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - expat=2.6.4
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.12.1
  - icu=73.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=8.4.0
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=2.2.4
  - numpy-base=2.2.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.0
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - wheel=0.45.1
  - xcb-util-cursor=0.1.4
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.6.0
      - av==14.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - clip==1.0
      - ffmpeg==1.4
      - filelock==3.18.0
      - fsspec==2025.3.2
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - huggingface-hub==0.30.1
      - idna==3.10
      - iopath==0.1.10
      - jinja2==3.1.6
      - joblib==1.4.2
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.11.0.86
      - parameterized==0.9.0
      - peft==0.15.2
      - portalocker==3.1.1
      - psutil==7.0.0
      - pytorchvideo==0.1.5
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - timm==1.0.15
      - tokenizers==0.21.1
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.50.3
      - triton==3.2.0
      - typing-extensions==4.13.0
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - yacs==0.1.8
prefix: /home/xinyi/anaconda3/envs/camp-vqa
